@startuml
title Теплый дом Telemetry Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

System(WarmHouseSystem, "Теплый дом", "Система удаленного управления теплым домом")
Container_Boundary(WarmHouseSystem, "Теплый дом") {
  Container(TelemetryService, "Telemetry Service", "Node.js", "Сбор и обработка телеметрии от устройств")
  Container(MessageBroker, "Шина данных между сервисами", "RabbitMQ", "Управление сообщениями между сервисами")
}

Container(TelemetryService, "Telemetry Service") {
 Component(subscribeService, "Подписка на события", "Получение сообщений телеметрии")
 Component(emitService, "Рассылка данных пользователям", "Рассылка данных")
}

Rel(MessageBroker, TelemetryService, "Подписка на телеметрию")
@enduml
