@startuml
title Warmhouse Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the system")
Person(admin, "Administrator", "An administrator managing the system")
System(WarmhouseSystem, "Warm house", "Remote control of heating in the house")

Container_Boundary(WarmhouseSystem, "Warm house System") {
  Container(HeatingSystem, "Heating Application", "Go", "Heating system control")
  Container(Database, "Database", "PostgreSQL", "Stores sensor data")
}

System_Ext(sensors, "Heating system", "External system control sensors")

Rel(user, HeatingSystem, "Uses the system")
Rel(admin, HeatingSystem,"Manages the system")
Rel(HeatingSystem, Database, "Reads/Writes/Updates/Deletes sensor data")
Rel(HeatingSystem, sensors, "Control of sensors")

@enduml
